on:
  push:
    branches:
      - main

name: Build

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Get nginx-unprivileged base image tag
        id: image-tag
        run: echo "TAG_NAME=$(python .github/workflows/get_tag.py)" >> "$GITHUB_OUTPUT"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure docker metadata  # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/unraid/nginx-otel
          tags: |
            type=raw,value=${{ steps.image-tag.outputs.TAG_NAME }}
      
      - name: Build and push NGINX image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
