on:
  push:
    branches:
      - main

name: Build

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:
      # Using git context for build, no need to check out https://github.com/docker/build-push-action#git-context
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure docker metadata  # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/unraid/nginx-otel
          tags: |
            type=raw,value=1.25.3-alpine3.18-slim
      # IMPORTANT: Manual tag version!
      
      - name: Build and push NGINX image
        uses: docker/build-push-action@v5
        with:
          file: configs/nginx.Dockerfile
          push: true
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
